name: kd_scanner
description: A Flutter plugin for mobile devices to scan barcodes and QR codes.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter    
  plugin_platform_interface: ^1.0.2
  js: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.github.kokemus.kd_scanner
        pluginClass: KdScannerPlugin
      ios:
        pluginClass: KdScannerPlugin
      web:
        pluginClass: KdScannerPlugin
        fileName: kd_scanner_web.dart

  assets:
    - packages/kd_scanner/js/barcode_scanner.js
