name: kd_scanner
description: A Flutter plugin for mobile devices to scan barcodes and QR codes.
version: 0.2.0-nullsafety.0
publish_to: none
author:
homepage:

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter    
  plugin_platform_interface: ^1.1.0-nullsafety
  barcode_scanner:
    git:
      url: git://github.com/kokemus/barcode_scanner.git
      ref: 0.2.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.github.kokemus.kd_scanner
        pluginClass: KdScannerPlugin
      ios:
        pluginClass: KdScannerPlugin
      web:
        pluginClass: KdScannerPlugin
        fileName: kd_scanner_web.dart
